import { Fredoka } from "next/font/google";
// Styles
import "./globals.css";
// Components
import { BackImage } from "./(shared)/_components";

const inter = Fredoka({ subsets: ["latin"] });

export const metadata = {
  title: "Find four App",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BackImage />
        {children}
      </body>
    </html>
  );
}
