import Head from "next/head";
// Components
import { Board } from "@/modules/gameboard/components/Board";
import { Title } from "@/shared/components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Find Four App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Title title="Find Four App" size="large" />
        <Board />
      </main>
    </>
  );
}
